MCTS:
  MCTS_exploration: 1
  rollout_duration: 1
  epsilon: 0.05

neural_net:
  hidden_layers: 1
  neurons_per_layer: 25
  activation_function: relu # sigmoid/tanh/relu/linear

training:
  episodes: 10000
  optimizer: adam # adagrad/sgd/RMSPROP/adam
  epochs: 50
  learning_rate: 0.01
  RBUF_sample_size: 1024

hex:
  board_size: 5 #creates nxn board (between 3 and 10)

M: 50 #Save interval of neural nets
nr_games: 1 #Number of games to play in TOPP
