MCTS:
  MCTS_exploration: 1.0
  rollout_duration: 1
  epsilon: 1.0

neural_net:
  hidden_layers: 2
  neurons_per_layer: 50
  activation_function: tanh # sigmoid/tanh/relu/linear

training:
  episodes: 10000
  optimizer: adam # adagrad/sgd/RMSPROP/adam
  epochs: 50
  learning_rate: 0.02
  RBUF_sample_size: 4000

hex:
  board_size: 7 #creates nxn board (between 3 and 10)

M: 50 #Save interval of neural nets
G: 2 #Number of games to play in TOPP
visualize: True #Whether to visualize the game or not
