MCTS:
  MCTS_exploration: 1.5
  rollout_duration: 2.0
  epsilon_decay_rate: 0.0
  epsilon: 1.0

neural_net:
  hidden_layers: 1
  neurons_per_layer: 26
  activation_function: relu # sigmoid/tanh/relu/linear

training:
  episodes: 200
  optimizer: adam # adagrad/sgd/RMSPROP/adam
  epochs: 150
  learning_rate: 0.01
  RBUF_sample_size: 1000

hex:
  board_size: 5 #creates nxn board (between 3 and 10)

M: 25 #Save interval of neural nets
G: 50 #Number of games to play in TOPP
visualize: True #Whether to visualize the game or not
