MCTS:
  MCTS_exploration: 1.5
  rollout_duration: 8.0
  epsilon_decay_rate: 0.0
  epsilon: 1.0

neural_net:
  hidden_layers: 4
  neurons_per_layer: 99
  activation_function: tanh # sigmoid/tanh/relu/linear

training:
  episodes: 325
  optimizer: adam # adagrad/sgd/RMSPROP/adam
  epochs: 150
  learning_rate: 0.00001
  RBUF_sample_size: 200

hex:
  board_size: 7 #creates nxn board (between 3 and 10)

M: 5 #Save interval of neural nets
G: 1 #Number of games to play in TOPP
visualize: False #Whether to visualize the game or not
