MCTS:
  MCTS_exploration: 1
  rollouts: 1000
  epsilon: 0.05

neural_net:
  hidden_layers: 3
  neurons_per_layer: 25
  weight_bias_initial_range: [-0.1, 0.1]
  activation_function: sigmoid # sigmoid/tanh/relu/linear

training:
  episodes: 10
  optimizer: RMSPROP # adagrad/sgd/RMSPROP/adam
  epochs: 25
  learning_rate: 0.02
  RBUF_sample_size: 50

hex:
  board_size: 5 #creates nxn board (between 3 and 10)
