MCTS:
  MCTS_exploration: 1
  rollouts: 200
  epsilon: 0.05

neural_net:
  hidden_layers: 2
  neurons_per_layer: 10
  weight_bias_initial_range: [-0.1, 0.1]
  activation_function: tanh # sigmoid/tanh/relu/linear

training:
  episodes: 50
  optimizer: adam # adagrad/sgd/RMSPROP/adam
  epochs: 25
  learning_rate: 0.01
  RBUF_sample_size: 400

hex:
  board_size: 5 #creates nxn board (between 3 and 10)
